platform :ios, ‘7.0’

pod "AFNetworking", "~> 2.0"
pod "MJExtension", "~> 2.5.14"
pod "Masonry", "~> 0.6.3"
pod "SDWebImage", "~> 3.7.3"
pod "MBProgressHUD", "~> 0.9.1"
pod "Base64nl", "~> 1.2"
pod "MJRefresh", "~> 3.1.0"
pod "IQKeyboardManager", "~> 2.5.0"
